// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_6jvfrGnIwO9f-oUs8xHznkcmn69gHE',
    appId: '1:822614243355:web:f7a9e025ecf66c6f71e0be',
    messagingSenderId: '822614243355',
    projectId: 'nttu-d42ee',
    authDomain: 'nttu-d42ee.firebaseapp.com',
    storageBucket: 'nttu-d42ee.appspot.com',
    measurementId: 'G-YJMT4EFCBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6v8aTs2K45iVFjXqI4WhqYVlnED0cpjQ',
    appId: '1:822614243355:android:4c893e21c564643471e0be',
    messagingSenderId: '822614243355',
    projectId: 'nttu-d42ee',
    storageBucket: 'nttu-d42ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_4q7Q-sBmWHkdXdwHS7DdiZ8gtbOWps',
    appId: '1:822614243355:ios:88ebfaae84bfd6c371e0be',
    messagingSenderId: '822614243355',
    projectId: 'nttu-d42ee',
    storageBucket: 'nttu-d42ee.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
